---
# To use this run:
#   uv run pre-commit install
# If you change, run:
#   uv run pre-commit clean && uv run pre-commit install --install-hooks

repos:
  # update versions of pre-commit-hooks from pyproject.toml
  - repo: local
    hooks:
      - id: update-prettier-version-from-pyproject-toml
        name: update prettier version in pre-commit
        entry: /bin/bash -c "dev-scripts/update-pre-commit-versions-from-pyproject-toml.sh prettier"
        language: script
        require_serial: true
      - id: update-shellcheck-version-from-pyproject-toml
        name: update shellcheck version in pre-commit
        entry: /bin/bash -c "dev-scripts/update-pre-commit-versions-from-pyproject-toml.sh shellcheck"
        language: script
        require_serial: true
      - id: update-docformatter-version-from-pyproject-toml
        name: update docformatter version in pre-commit
        entry: /bin/bash -c "dev-scripts/update-pre-commit-versions-from-pyproject-toml.sh docformatter"
        language: script
        require_serial: true
      - id: update-ruff-version-from-pyproject-toml
        name: update ruff version in pre-commit
        entry: /bin/bash -c "dev-scripts/update-pre-commit-versions-from-pyproject-toml.sh ruff"
        language: script
        require_serial: true
      - id: update-mypy-version-from-pyproject-toml
        name: update mypy version in pre-commit
        entry: /bin/bash -c "dev-scripts/update-pre-commit-versions-from-pyproject-toml.sh mypy"
        language: script
        require_serial: true
      - id: update-hadolint-version-from-pyproject-toml
        name: update hadolint version in pre-commit
        entry: /bin/bash -c "dev-scripts/update-pre-commit-versions-from-pyproject-toml.sh hadolint"
        language: script
        require_serial: true
      - id: update-action-validator-version-from-pyproject-toml
        name: update action-validator version in pre-commit
        entry: /bin/bash -c "dev-scripts/update-pre-commit-versions-from-pyproject-toml.sh action-validator"
        language: script
        require_serial: true
      - id: update-yamllint-version-from-pyproject-toml
        name: update yamllint version in pre-commit
        entry: /bin/bash -c "dev-scripts/update-pre-commit-versions-from-pyproject-toml.sh yamllint"
        language: script
        require_serial: true
      - id: update-uv-pre-commit-version-from-pyproject-toml
        name: update uv-pre-commit version in pre-commit
        entry: /bin/bash -c "dev-scripts/update-pre-commit-versions-from-pyproject-toml.sh uv-pre-commit"
        language: script
        require_serial: true

  # basic checks (see here: https://pre-commit.com/hooks.html)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  # ruff - linting + formatting
  # Note: ruff installed in pyproject dev group
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        name: ruff
        language_version: python3.11
      - id: ruff-format
        name: ruff-format
        language_version: python3.11

  # mypy - lint-like type checking
  # Note: mypy installed in pyproject dev group
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        name: mypy
        language_version: python3.11
        additional_dependencies:
          [
            "matplotlib-stubs",
            "pandas-stubs",
            "ml-dtypes",
            "types-Pillow",
            "types-python-dateutil",
            "types-pytz",
            "types-PyYAML",
            "types-requests",
            "types-tqdm",
            "boto3-stubs",
            "mypy_boto3_s3",
          ]
        types: [python]

  # hadolint - check dockerfiles (run from docker itself)
  # note: match anything named *ockerfile* in docker/ directory
  # note: files is a regex so escale the / and * is not a wildcard
  #       but is "zero or more", and . is more of a wildcard
  # note: you have to say a types of "file" or it will
  #       ignore non-standard named Dockerfiles
  # note: this hook is EXTREMELY picky so be very careful when change
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        description: Runs hadolint Docker image to lint Dockerfiles
        language: docker_image
        types: [file]
        entry: ghcr.io/hadolint/hadolint hadolint
        files: ^docker\/.*(d|D)ockerfile.*$

  # prettier - formatting JS, CSS, JSON, Markdown, ...
  # Note: v2.5.1 supports node v12 (ubuntu 22.04)
  # Note: install prettier tool with:
  #   sudo npm install --save-dev --save-exact prettier
  # Note: prettier will fight with yamllint on spaces before inline comment
  #       the world seems to prefer two, but prettier is stubborn on this
  #       (https://github.com/prettier/prettier/issues/6780), so best
  #       to just avoid inline comments
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: \.(md|json|toml|yml|yaml)$
        exclude: ^uv.lock

  # docformatter - formats docstrings to follow PEP 257
  # Note: docformatter requires version <4.0.0 until next release:
  #   https://github.com/PyCQA/docformatter/issues/293
  # Note: install docformatter in pyproject dev group
  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        name: docformatter
        args:
          [
            -r,
            -i,
            --pre-summary-newline,
            --make-summary-multi-line,
            --wrap-summaries,
            "88",
            src,
          ]

  # check bash/shell scripts
  # note: install shellcheck with:
  #   sudo apt install shellcheck (0.8.0 for ubuntu 22.04)
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        # Optional: Adjust severity level
        args: ["--severity=warning"]

  # yamllint
  # checks for valid yaml code
  # Note: see note above on inline comment fights with prettier
  #       although we could override the conflice by setting yamllint
  #       config to `comments: min-spaces-from-comment: 1`, this is
  #       asking for trouble with github actions, so best to just
  #       use comments before the line, not inline for now
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        # Optional: Use custom yamllint config file
        args: [--strict, -c=.yamllint]

  # check github actions yaml
  # note: install action-validator with:
  #   sudo npm install -g @action-validator/core @action-validator/cli --save-dev
  # note: checks workflows only, not actions
  - repo: https://github.com/mpalmer/action-validator
    rev: v0.5.4
    hooks:
      - id: action-validator
        name: Validate GitHub Actions workflows
        description: "Validate GitHub Actions workflows"
        entry: action-validator
        language: rust
        files: '.github/workflows/.*\.ya?ml'

  # ensure lock file is up to date
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.27
    hooks:
      - id: uv-lock
